import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Front end Rusty",
  description: "Generated by DHYEY",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
  {/* this is our entire web app*/}
 

      <body className={'${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden'}>
        {children}</body>
    </html>
  );
}
